#!/usr/bin/env python3
"""Generated by chrono-distribution; bootstrap the pinned installer, then delegate."""
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile


def unique(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError('duplicate JSON member: ' + key)
        result[key] = value
    return result


def main():
    if len(sys.argv) != 2:
        raise ValueError('usage: install.py HOST_ROOT')
    root = Path(sys.argv[1]).resolve()
    cfg = json.loads((root / '.chrono-harness/distribution.json').read_text(), object_pairs_hook=unique)
    if cfg['schema'] != 'chrono-install/v1':
        raise ValueError('unsupported install schema')
    system = {'Darwin': 'macos', 'Linux': 'linux'}.get(platform.system())
    arch = {'arm64': 'aarch64', 'aarch64': 'aarch64', 'x86_64': 'x86_64', 'AMD64': 'x86_64'}.get(platform.machine())
    key = str(system) + '-' + str(arch)
    asset = cfg['installers'][key]
    if asset['file'] != 'chrono-distribution-' + key:
        raise ValueError('installer platform mismatch')
    with tempfile.TemporaryDirectory(prefix='chrono-install-') as tmp:
        tool = Path(tmp) / 'chrono-distribution'
        source = cfg['source']
        if source['kind'] == 'https':
            base = source['base_url']
            if not base.startswith('https://') or any(c in base for c in '?@#\n\r'):
                raise ValueError('invalid HTTPS release source')
            subprocess.run([source['curl'], '--disable', '--fail', '--location', '--silent', '--show-error',
                            '--proto', '=https', '--proto-redir', '=https', '--connect-timeout', '30',
                            '--max-time', '300', '--output', str(tool), '--url', base.rstrip('/') + '/' + asset['file']], check=True)
        elif source['kind'] == 'directory' and Path(source['path']).is_absolute():
            shutil.copyfile(Path(source['path']) / asset['file'], tool)
        else:
            raise ValueError('unsupported release source')
        digest = hashlib.sha256()
        with tool.open('rb') as stream:
            for chunk in iter(lambda: stream.read(65536), b''):
                digest.update(chunk)
        if tool.stat().st_size != asset['size'] or digest.hexdigest() != asset['sha256']:
            raise ValueError('installer integrity mismatch')
        os.chmod(tool, 0o755)
        return subprocess.run([str(tool), 'install', '--host-root', str(root)]).returncode


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError) as error:
        print('E_DISTRIBUTION_BOOTSTRAP:', error, file=sys.stderr)
        sys.exit(1)
